services:
  server:
    build: .
    container_name: bia
    ports:
      - 3001:8080
    depends_on:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: uqDbcNFy4koc1oIiw4Oe
      DB_HOST: bia.c0d0m80yymjy.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
    

